name: test

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: sleep 30s && return 0
